### PR TITLE
Update README with minor changes

### PR DESCRIPTION
**Pull request by aqsmith08**
Updated the README to include baseball (which I believe is available per the public Slack conversation) and fixed a broken link that took you to a 404 error.

### CODE REVIEW

**Comment by dthyresson** [comment]
@aqsmith08 's change look good to :shipit: to me.

Comments? @Btibert3, @tcash21, @batpigandme?

**Comment by tcash21** [comment]
+1

**Comment by aqsmith08** [comment]
Sorry all. I made a couple more (minor) changes. Hope that's okay.

**Comment by tcash21** [comment]
All good! :+1: for Hadley Style too.

**Pull request merged**
